export interface SeedPerson {
  name: string;
  email: string;
  password: string;
  gender: 'female' | 'male';
  dob: string;
  city: string;
  country: string;
  lat: number;
  lng: number;
  bio: string;
  intention: 'long_term' | 'serious' | 'friendship' | 'casual' | 'not_sure';
  interests: string[];
  showMe: 'female' | 'male' | 'everyone';
  ageMin: number;
  ageMax: number;
  verified: boolean;
  lastActiveDaysAgo: number;
}

export const SEED_INTERESTS: { slug: string; name: string; emoji: string; category: string }[] = [
  { slug: 'anime', name: 'Anime', emoji: '🌸', category: 'pop_culture' },
  { slug: 'manga', name: 'Manga', emoji: '📚', category: 'pop_culture' },
  { slug: 'movies', name: 'Movies', emoji: '🎬', category: 'pop_culture' },
  { slug: 'gaming', name: 'Gaming', emoji: '🎮', category: 'pop_culture' },
  { slug: 'music', name: 'Music', emoji: '🎵', category: 'music' },
  { slug: 'afrobeats', name: 'Afrobeats', emoji: '🥁', category: 'music' },
  { slug: 'singing', name: 'Singing', emoji: '🎤', category: 'music' },
  { slug: 'football', name: 'Football', emoji: '⚽', category: 'sports' },
  { slug: 'basketball', name: 'Basketball', emoji: '🏀', category: 'sports' },
  { slug: 'fitness', name: 'Fitness', emoji: '💪', category: 'sports' },
  { slug: 'travel', name: 'Travel', emoji: '✈️', category: 'lifestyle' },
  { slug: 'cooking', name: 'Cooking', emoji: '🍲', category: 'lifestyle' },
  { slug: 'foodie', name: 'Foodie', emoji: '🍛', category: 'lifestyle' },
  { slug: 'fashion', name: 'Fashion', emoji: '👗', category: 'lifestyle' },
  { slug: 'photography', name: 'Photography', emoji: '📷', category: 'arts' },
  { slug: 'art', name: 'Art', emoji: '🎨', category: 'arts' },
  { slug: 'reading', name: 'Reading', emoji: '📖', category: 'arts' },
  { slug: 'dancing', name: 'Dancing', emoji: '💃', category: 'arts' },
  { slug: 'technology', name: 'Technology', emoji: '💻', category: 'tech' },
  { slug: 'startups', name: 'Startups', emoji: '🚀', category: 'tech' },
  { slug: 'nature', name: 'Nature', emoji: '🌿', category: 'lifestyle' },
  { slug: 'volunteering', name: 'Volunteering', emoji: '🤝', category: 'social' },
  { slug: 'coffee', name: 'Coffee', emoji: '☕', category: 'lifestyle' },
  { slug: 'wellness', name: 'Wellness', emoji: '🧘', category: 'lifestyle' },
];

export const SEED_PEOPLE: SeedPerson[] = [
  {
    name: 'Amara Okonkwo',
    email: 'amara@kokoro.test',
    password: 'Password123',
    gender: 'female',
    dob: '1997-04-12',
    city: 'Lagos',
    country: 'Nigeria',
    lat: 6.5244,
    lng: 3.3792,
    bio: 'Afrobeats dancer and foodie exploring Lagos one spot at a time. Looking for someone kind, ambitious, and ready for real conversations. 🌸',
    intention: 'long_term',
    interests: ['afrobeats', 'dancing', 'cooking', 'travel', 'fashion', 'movies'],
    showMe: 'male',
    ageMin: 24,
    ageMax: 34,
    verified: true,
    lastActiveDaysAgo: 0,
  },
  {
    name: 'Kwame Mensah',
    email: 'kwame@kokoro.test',
    password: 'Password123',
    gender: 'male',
    dob: '1995-09-03',
    city: 'Accra',
    country: 'Ghana',
    lat: 5.6037,
    lng: -0.187,
    bio: 'Software engineer by day, photographer on weekends. I love quiet beaches, good coffee, and long talks about everything and nothing.',
    intention: 'serious',
    interests: ['technology', 'photography', 'coffee', 'travel', 'music', 'startups'],
    showMe: 'female',
    ageMin: 22,
    ageMax: 33,
    verified: true,
    lastActiveDaysAgo: 1,
  },
  {
    name: 'Zanele Dlamini',
    email: 'zanele@kokoro.test',
    password: 'Password123',
    gender: 'female',
    dob: '1999-11-22',
    city: 'Johannesburg',
    country: 'South Africa',
    lat: -26.2041,
    lng: 28.0473,
    bio: 'Medical student, marathon runner, and weekend painter. Big on family, fitness, and Friday-night movies. Looking for my co-adventurer.',
    intention: 'long_term',
    interests: ['fitness', 'art', 'movies', 'reading', 'nature', 'cooking'],
    showMe: 'male',
    ageMin: 24,
    ageMax: 35,
    verified: true,
    lastActiveDaysAgo: 2,
  },
  {
    name: 'Thabo Nkosi',
    email: 'thabo@kokoro.test',
    password: 'Password123',
    gender: 'male',
    dob: '1996-02-18',
    city: 'Cape Town',
    country: 'South Africa',
    lat: -33.9249,
    lng: 18.4241,
    bio: 'Chef with a thing for sunset hikes and vinyl records. I will absolutely cook for you on the third date. Bring your appetite 🍲',
    intention: 'serious',
    interests: ['cooking', 'foodie', 'music', 'nature', 'travel', 'fitness'],
    showMe: 'female',
    ageMin: 23,
    ageMax: 34,
    verified: false,
    lastActiveDaysAgo: 0,
  },
  {
    name: 'Fatou Diallo',
    email: 'fatou@kokoro.test',
    password: 'Password123',
    gender: 'female',
    dob: '1998-07-09',
    city: 'Dakar',
    country: 'Senegal',
    lat: 14.7167,
    lng: -17.4677,
    bio: 'Fashion designer and anime fan — yes, both. Chasing creativity and calm. Tell me about the last thing that made you smile.',
    intention: 'friendship',
    interests: ['fashion', 'anime', 'art', 'music', 'coffee', 'reading'],
    showMe: 'everyone',
    ageMin: 21,
    ageMax: 32,
    verified: true,
    lastActiveDaysAgo: 3,
  },
  {
    name: 'David Mwangi',
    email: 'david@kokoro.test',
    password: 'Password123',
    gender: 'male',
    dob: '1994-12-01',
    city: 'Nairobi',
    country: 'Kenya',
    lat: -1.2921,
    lng: 36.8219,
    bio: 'Fintech founder. Football Sundays, hiking Saturdays, and building the future in between. Looking for someone genuine and driven.',
    intention: 'long_term',
    interests: ['startups', 'technology', 'football', 'fitness', 'travel', 'coffee'],
    showMe: 'female',
    ageMin: 24,
    ageMax: 34,
    verified: true,
    lastActiveDaysAgo: 1,
  },
  {
    name: 'Aisha Bello',
    email: 'aisha@kokoro.test',
    password: 'Password123',
    gender: 'female',
    dob: '2000-03-15',
    city: 'Abuja',
    country: 'Nigeria',
    lat: 9.0765,
    lng: 7.3986,
    bio: 'Gamer girl 🎮 and manga reader who also loves a great night out. If you can make me laugh, you are already halfway there.',
    intention: 'casual',
    interests: ['gaming', 'manga', 'anime', 'music', 'movies', 'foodie'],
    showMe: 'everyone',
    ageMin: 20,
    ageMax: 30,
    verified: false,
    lastActiveDaysAgo: 0,
  },
  {
    name: 'Eric Tumusiime',
    email: 'eric@kokoro.test',
    password: 'Password123',
    gender: 'male',
    dob: '1997-08-27',
    city: 'Kampala',
    country: 'Uganda',
    lat: 0.3476,
    lng: 32.5825,
    bio: 'Veterinarian, wildlife lover, and amateur guitarist. Quiet weekends, loud laughter. Searching for a kind heart and a curious mind.',
    intention: 'serious',
    interests: ['nature', 'music', 'singing', 'travel', 'volunteering', 'coffee'],
    showMe: 'female',
    ageMin: 22,
    ageMax: 33,
    verified: true,
    lastActiveDaysAgo: 4,
  },
  {
    name: 'Vanessa Etienne',
    email: 'vanessa@kokoro.test',
    password: 'Password123',
    gender: 'female',
    dob: '1998-05-30',
    city: 'Yaoundé',
    country: 'Cameroon',
    lat: 3.848,
    lng: 11.5021,
    bio: 'Marketing lead, wellness enthusiast, and dancing-floor regular. I believe great love starts with great friendship. 💃',
    intention: 'long_term',
    interests: ['dancing', 'wellness', 'afrobeats', 'fashion', 'travel', 'cooking'],
    showMe: 'male',
    ageMin: 24,
    ageMax: 35,
    verified: true,
    lastActiveDaysAgo: 0,
  },
  {
    name: 'Mohamed Traoré',
    email: 'mohamed@kokoro.test',
    password: 'Password123',
    gender: 'male',
    dob: '1995-10-10',
    city: 'Abidjan',
    country: "Côte d'Ivoire",
    lat: 5.36,
    lng: -4.0083,
    bio: 'Architect who sketches buildings by day and dreams up road trips by night. Basketball, afrobeats, and amazing food. Let’s explore.',
    intention: 'serious',
    interests: ['art', 'basketball', 'afrobeats', 'travel', 'foodie', 'photography'],
    showMe: 'female',
    ageMin: 23,
    ageMax: 34,
    verified: false,
    lastActiveDaysAgo: 2,
  },
  {
    name: 'Grace Wanjiru',
    email: 'grace@kokoro.test',
    password: 'Password123',
    gender: 'female',
    dob: '1996-01-25',
    city: 'Nairobi',
    country: 'Kenya',
    lat: -1.2864,
    lng: 36.8172,
    bio: 'News journalist with a soft spot for bookshops and rainy Sundays. I value honesty, curiosity, and people who text back.',
    intention: 'long_term',
    interests: ['reading', 'coffee', 'travel', 'movies', 'volunteering', 'music'],
    showMe: 'male',
    ageMin: 25,
    ageMax: 36,
    verified: true,
    lastActiveDaysAgo: 5,
  },
  {
    name: 'Lungelo Maseko',
    email: 'lungelo@kokoro.test',
    password: 'Password123',
    gender: 'male',
    dob: '1999-06-19',
    city: 'Durban',
    country: 'South Africa',
    lat: -29.8587,
    lng: 31.0218,
    bio: 'Personal trainer and part-time DJ. Fitness, family, and fun. Looking for someone to share playlists, sunsets, and goals.',
    intention: 'casual',
    interests: ['fitness', 'music', 'dancing', 'football', 'foodie', 'nature'],
    showMe: 'female',
    ageMin: 21,
    ageMax: 31,
    verified: false,
    lastActiveDaysAgo: 1,
  },
];
